### ISSUE TITLE
AssertionError when submitting DTC

### ISSUE THREAD

**Issue by awindler** [tbohne/obd_ontology#23]
This AssertionError appears when submitting a DTC:

![grafik](https://user-images.githubusercontent.com/35371884/219648703-aa72fc25-69cd-40e3-ada1-67fca03e8cfc.png)

**Comment by tbohne** [comment]
I suppose you got this when entering a DTC with a third digit higher than 7. This is due to the fact that those DTCs are not defined based on the standard. However, it's of course possible that a user enters such a DTC anyway.
I fixed it by adding another subsystem for unknown cases. After updating the `dtc_parser`, it should work.
